'use client';

import ButtonChangeLanguage from '@/components/Translate/ButtonChangeLanguage';
import './global.css';
import { Providers } from './utils/provider';
import React from 'react';
import { getCssStyleVariable } from '@/helper/methods/style/getCssStyleVariable';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [localLanguage, setLocalLanguage] = React.useState<
    string | null | undefined
  >(null);

  React.useEffect(() => {
    if (typeof window !== 'undefined') {
      const lang = localStorage.getItem('lang');

      if (lang) {
        setLocalLanguage(lang);
      } else {
        setLocalLanguage(undefined);
      }
    }
  }, []);

  // mocando uma troca de tema quando for partner/banker
  // agora faz quando entra na aplicação, mas posso fazer essa lógica numa request
  // ou verificar no localStorage
  const [primaryColor, setPrimaryColor] = React.useState<string>(''); // Cor inicial (vermelho)
  const [isPartner, setIsPartner] = React.useState<boolean>(false);

  function handleChangeAppColor(color: string) {
    setPrimaryColor(color);
    document.documentElement.style.setProperty('--primary-color', color);
  }

  React.useEffect(() => {
    setTimeout(() => {
      if (isPartner) {
        handleChangeAppColor('#12f');
      } else {
        const defaultColor = getCssStyleVariable('--primary-color');

        handleChangeAppColor(defaultColor);
      }
    }, 3000);
  });

  return (
    <html lang="en">
      <head>
        <title>Bankers dressing in cropped</title>
        <meta httpEquiv="Content-Type" content="text/html;charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="contente" />
        {/* fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          cross-origin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className="font-roboto">
        <Providers>
          {/* somente monta o botão e os componentes da aplicação após verificar no localStorage se tem um lang
           e fazer um get para trazer o arquivo de tradução 
           com esse if evitamos que a tela dê um pulo na troca de uma idioma para o outro */}
          {(localLanguage || localLanguage === undefined) && (
            <ButtonChangeLanguage defaultLanguage={localLanguage} />
          )}
          {(localLanguage || localLanguage === undefined) && children}
        </Providers>
      </body>
    </html>
  );
}
